import { Ads } from "../interfaces/ad"

export const AdData:Ads[]=[
    {
        id:0,
        title:"German shepred dog",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'1200',
        ago:'2 weeks ago',
        image:'/assets/download.jpg',
    },
    {
        id:0,
        title:"Persian Cat",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'14200',
        ago:'2 weeks ago',
        image:'/assets/catu.jpg',
    },
    {
        id:0,
        title:"Dove pakistani",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'1200',
        ago:'2 weeks ago',
        image:'/assets/dove.jpg',
    },
    {
        id:0,
        title:"Parrote Indian ",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'1200',
        ago:'2 weeks ago',
        image:'/assets/parrote.jpg',
    },
    {
        id:0,
        title:"Persian Cat",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'14200',
        ago:'2 weeks ago',
        image:'/assets/catu.jpg',
    },
    {
        id:0,
        title:"German shepred dog",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'1200',
        ago:'2 weeks ago',
        image:'/assets/download.jpg',
    },
    {
        id:0,
        title:"Parrote Indian ",
        tag:true,
        location:'Model town Bahawalnagar',
        price:'1200',
        ago:'2 weeks ago',
        image:'/assets/parrote.jpg',
    },
]